ALTER TABLE expense_notes
    MODIFY status ENUM('PENDING','PAID','CANCELLED','APPROVED','REJECTED','REIMBURSED') NOT NULL DEFAULT 'PENDING';

UPDATE expense_notes SET status = 'REIMBURSED' WHERE status = 'PAID';
UPDATE expense_notes SET status = 'REJECTED' WHERE status = 'CANCELLED';

ALTER TABLE expense_notes
    MODIFY status ENUM('PENDING','APPROVED','REJECTED','REIMBURSED') NOT NULL DEFAULT 'PENDING';
