CREATE TABLE IF NOT EXISTS erp_vat_periods (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    opening_credit DECIMAL(20,3) NOT NULL DEFAULT 0,
    vat_collected DECIMAL(20,3) NOT NULL DEFAULT 0,
    vat_deductible DECIMAL(20,3) NOT NULL DEFAULT 0,
    vat_payable DECIMAL(20,3) NOT NULL DEFAULT 0,
    closing_credit DECIMAL(20,3) NOT NULL DEFAULT 0,
    status ENUM('DRAFT','REVIEWED','LOCKED','FILED') NOT NULL DEFAULT 'DRAFT',
    source_period_id BIGINT UNSIGNED NULL,
    reviewed_by INT NULL,
    reviewed_at DATETIME NULL,
    locked_by INT NULL,
    locked_at DATETIME NULL,
    filed_by INT NULL,
    filed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    UNIQUE KEY uq_vat_period_company_month(user_id,period_start,period_end),
    KEY idx_vat_period_company_status(user_id,status,period_end),
    CONSTRAINT chk_vat_period_values CHECK(opening_credit>=0 AND vat_collected>=0 AND vat_deductible>=0 AND vat_payable>=0 AND closing_credit>=0),
    CONSTRAINT chk_vat_period_single_result CHECK(vat_payable=0 OR closing_credit=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
