ALTER TABLE users
  ADD COLUMN role ENUM('ADMINISTRATOR','COMMERCIAL','STOCK','ACCOUNTING')
  NOT NULL DEFAULT 'ADMINISTRATOR'
  AFTER fodec;

UPDATE users
SET role = 'ADMINISTRATOR'
WHERE role IS NULL OR TRIM(role) = '';
