CREATE TABLE erp_background_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    created_by INT NOT NULL,
    job_type VARCHAR(64) NOT NULL,
    status ENUM('QUEUED','RUNNING','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'QUEUED',
    payload_json LONGTEXT NOT NULL CHECK (JSON_VALID(payload_json)),
    result_json LONGTEXT NULL CHECK (result_json IS NULL OR JSON_VALID(result_json)),
    request_hash CHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts TINYINT UNSIGNED NOT NULL DEFAULT 3,
    progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
    available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at DATETIME NULL,
    locked_by VARCHAR(128) NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_background_job_request (user_id,job_type,idempotency_key),
    KEY idx_background_job_claim (status,available_at,id),
    KEY idx_background_job_tenant (user_id,created_at,id),
    KEY idx_background_job_stale (status,locked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
