CREATE TABLE erp_contribution_configs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    contribution ENUM('TCL','TFP','FOPROLOS') NOT NULL,
    basis_kind ENUM('TURNOVER','GROSS_PAYROLL','MANUAL') NOT NULL,
    rate DECIMAL(10,6) NOT NULL,
    legal_basis VARCHAR(255) NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    UNIQUE KEY uq_contribution_config(user_id,contribution,effective_from),
    KEY idx_contribution_config_effective(user_id,contribution,effective_from,effective_to),
    CONSTRAINT chk_contribution_rate CHECK(rate BETWEEN 0 AND 100),
    CONSTRAINT chk_contribution_config_dates CHECK(effective_to IS NULL OR effective_to>=effective_from)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE erp_contribution_periods (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    config_id BIGINT UNSIGNED NOT NULL,
    contribution ENUM('TCL','TFP','FOPROLOS') NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    basis_kind ENUM('TURNOVER','GROSS_PAYROLL','MANUAL') NOT NULL,
    basis_amount DECIMAL(20,3) NOT NULL,
    rate DECIMAL(10,6) NOT NULL,
    calculated_amount DECIMAL(20,3) NOT NULL,
    status ENUM('DRAFT','REVIEWED','LOCKED','FILED') NOT NULL DEFAULT 'DRAFT',
    notes VARCHAR(500) NULL,
    reviewed_by INT NULL,
    reviewed_at DATETIME NULL,
    locked_by INT NULL,
    locked_at DATETIME NULL,
    filed_by INT NULL,
    filed_at DATETIME NULL,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    UNIQUE KEY uq_contribution_period(user_id,contribution,period_start,period_end),
    KEY idx_contribution_period_status(user_id,status,period_end),
    CONSTRAINT fk_contribution_period_config FOREIGN KEY(config_id) REFERENCES erp_contribution_configs(id),
    CONSTRAINT chk_contribution_period_values CHECK(basis_amount>=0 AND rate BETWEEN 0 AND 100 AND calculated_amount>=0),
    CONSTRAINT chk_contribution_period_dates CHECK(period_end>=period_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
