<?php
const FILING_ARCHIVE_REPORT_VERSION='2026.08.10-v1';
function archiveRows(mysqli $c,string $sql,string $types,array $args):array{$s=$c->prepare($sql);$s->bind_param($types,...$args);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$rows;}
function archiveCanonical(array $value):string{return json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR);}
function vatFilingPayload(mysqli $c,int $uid,int $entityId):array{
    $period=archiveRows($c,'SELECT * FROM erp_vat_periods WHERE id=? AND user_id=?','ii',[$entityId,$uid])[0]??null;if(!$period||$period['status']!=='FILED')throw new DomainException('VAT period must be filed before archiving');$from=$period['period_start'];$to=$period['period_end'];$p=[$uid,$from,$to];
    $invoices=archiveRows($c,"SELECT * FROM erp_invoices WHERE user_id=? AND invoice_date BETWEEN ? AND ? AND invoice_type IN('FACTURE','AVOIR') AND is_validated=1 ORDER BY id",'iss',$p);$invoiceIds=array_column($invoices,'id');
    $salesItems=$invoiceIds?archiveRows($c,'SELECT ii.* FROM erp_invoice_items ii JOIN erp_invoices i ON i.id=ii.invoice_id WHERE i.user_id=? AND i.invoice_date BETWEEN ? AND ? AND i.invoice_type IN(\'FACTURE\',\'AVOIR\') AND i.is_validated=1 ORDER BY ii.id','iss',$p):[];
    $purchases=archiveRows($c,"SELECT * FROM erp_supplier_invoices WHERE user_id=? AND invoice_date BETWEEN ? AND ? AND status IN('VALIDATED','PARTIALLY_PAID','PAID') ORDER BY id",'iss',$p);
    $purchaseItems=archiveRows($c,"SELECT sii.* FROM erp_supplier_invoice_items sii JOIN erp_supplier_invoices si ON si.id=sii.supplier_invoice_id WHERE si.user_id=? AND si.invoice_date BETWEEN ? AND ? AND si.status IN('VALIDATED','PARTIALLY_PAID','PAID') ORDER BY sii.id",'iss',$p);
    $source=['sales_invoices'=>$invoices,'sales_items'=>$salesItems,'supplier_invoices'=>$purchases,'supplier_items'=>$purchaseItems,'opening_source'=>$period['source_period_id']?archiveRows($c,'SELECT * FROM erp_vat_periods WHERE id=? AND user_id=?','ii',[(int)$period['source_period_id'],$uid]):[]];
    return['from'=>$from,'to'=>$to,'source'=>$source,'result'=>$period];
}
function accountingPeriodFilingPayload(mysqli $c,int $uid,int $entityId):array{
    $period=archiveRows($c,'SELECT * FROM erp_accounting_periods WHERE id=? AND user_id=?','ii',[$entityId,$uid])[0]??null;if(!$period||$period['status']!=='FILED')throw new DomainException('Accounting period must be filed before archiving');$from=$period['period_start'];$to=$period['period_end'];$p=[$uid,$from,$to];
    $source=['invoices'=>archiveRows($c,"SELECT * FROM erp_invoices WHERE user_id=? AND invoice_date BETWEEN ? AND ? ORDER BY id",'iss',$p),'invoice_items'=>archiveRows($c,"SELECT ii.* FROM erp_invoice_items ii JOIN erp_invoices i ON i.id=ii.invoice_id WHERE i.user_id=? AND i.invoice_date BETWEEN ? AND ? ORDER BY ii.id",'iss',$p),'supplier_invoices'=>archiveRows($c,"SELECT * FROM erp_supplier_invoices WHERE user_id=? AND invoice_date BETWEEN ? AND ? ORDER BY id",'iss',$p),'supplier_items'=>archiveRows($c,"SELECT sii.* FROM erp_supplier_invoice_items sii JOIN erp_supplier_invoices si ON si.id=sii.supplier_invoice_id WHERE si.user_id=? AND si.invoice_date BETWEEN ? AND ? ORDER BY sii.id",'iss',$p),'customer_payments'=>archiveRows($c,'SELECT * FROM erp_invoice_payments WHERE user_id=? AND payment_date BETWEEN ? AND ? ORDER BY id','iss',$p),'withholdings'=>archiveRows($c,"SELECT w.* FROM erp_invoice_withholdings w JOIN erp_invoices i ON i.id=w.invoice_id WHERE w.user_id=? AND i.invoice_date BETWEEN ? AND ? ORDER BY w.id",'iss',$p),'supplier_payments'=>archiveRows($c,'SELECT * FROM erp_supplier_payments WHERE user_id=? AND payment_date BETWEEN ? AND ? ORDER BY id','iss',$p),'expenses'=>archiveRows($c,'SELECT * FROM expense_notes WHERE user_id=? AND expense_date BETWEEN ? AND ? ORDER BY id','iss',$p),'stock_movements'=>archiveRows($c,'SELECT * FROM product_stock_movements WHERE user_id=? AND DATE(created_at) BETWEEN ? AND ? ORDER BY id','iss',$p)];
    $snapshots=archiveRows($c,'SELECT id,version,status,snapshot_json,snapshot_sha256,captured_by,captured_at FROM erp_accounting_period_snapshots WHERE period_id=? AND user_id=? ORDER BY version','ii',[$entityId,$uid]);return['from'=>$from,'to'=>$to,'source'=>$source,'result'=>['period'=>$period,'snapshots'=>$snapshots]];
}
function createFilingArchive(mysqli $c,int $uid,string $type,int $entityId,int $actor):array{
    $payload=$type==='VAT'?vatFilingPayload($c,$uid,$entityId):($type==='ACCOUNTING_PERIOD'?accountingPeriodFilingPayload($c,$uid,$entityId):throw new InvalidArgumentException('Unsupported filing archive type'));
    $sourceJson=archiveCanonical($payload['source']);$resultJson=archiveCanonical($payload['result']);$sourceHash=hash('sha256',$sourceJson);$resultHash=hash('sha256',$resultJson);$archiveHash=hash('sha256',FILING_ARCHIVE_REPORT_VERSION."\n".$type."\n".$entityId."\n".$sourceHash."\n".$resultHash);$count=array_sum(array_map('count',$payload['source']));
    $s=$c->prepare('SELECT COALESCE(MAX(filing_sequence),0)+1 next_sequence FROM erp_filing_archives WHERE user_id=? AND declaration_type=? AND source_entity_id=? FOR UPDATE');$s->bind_param('isi',$uid,$type,$entityId);$s->execute();$sequence=(int)$s->get_result()->fetch_assoc()['next_sequence'];$s->close();
    $s=$c->prepare('INSERT INTO erp_filing_archives(user_id,declaration_type,source_entity_id,filing_sequence,period_start,period_end,report_version,source_json,result_json,source_sha256,result_sha256,archive_sha256,source_row_count,captured_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->bind_param('isiissssssssii',$uid,$type,$entityId,$sequence,$payload['from'],$payload['to'],$version,$sourceJson,$resultJson,$sourceHash,$resultHash,$archiveHash,$count,$actor);$version=FILING_ARCHIVE_REPORT_VERSION;$s->execute();$id=(int)$s->insert_id;$s->close();return['id'=>$id,'filing_sequence'=>$sequence,'archive_sha256'=>$archiveHash,'source_sha256'=>$sourceHash,'result_sha256'=>$resultHash,'source_row_count'=>$count,'report_version'=>$version];
}
