<?php
header('Content-Type: application/json');require_once __DIR__.'/../config/response.php';require_once __DIR__.'/../config/db.php';require_once __DIR__.'/../config/audit.php';require_once __DIR__.'/../auth/auth_required.php';require_once __DIR__.'/../auth/role_helper.php';require_once __DIR__.'/contribution_service.php';require_once __DIR__.'/report_error.php';
try{if($_SERVER['REQUEST_METHOD']!=='POST')jsonResponse(['success'=>false,'message'=>'Method not allowed'],405);$auth=requireAuth();$uid=authTenantId($auth);$actorId=authActorId($auth);$d=json_decode(file_get_contents('php://input'),true)?:[];$contribution=strtoupper(trim((string)($d['contribution']??'')));$status=strtoupper(trim((string)($d['status']??'DRAFT')));$basis=contributionDecimal($d['basis_amount']??'','Basis amount');[$start,$end]=contributionDates(trim((string)($d['month']??'')));$notes=trim((string)($d['notes']??''));
    if(!in_array($contribution,['TCL','TFP','FOPROLOS'],true)||!in_array($status,['DRAFT','REVIEWED','LOCKED','FILED'],true))throw new InvalidArgumentException('Invalid contribution period');$conn=db();requirePermission($conn,$uid,'reports.view');$conn->begin_transaction();$config=resolveContributionConfig($conn,$uid,$contribution,$start);$amount=contributionAmount($basis,(string)$config['rate']);
    $s=$conn->prepare('SELECT * FROM erp_contribution_periods WHERE user_id=? AND contribution=? AND period_start=? AND period_end=? FOR UPDATE');$s->bind_param('isss',$uid,$contribution,$start,$end);$s->execute();$existing=$s->get_result()->fetch_assoc();$s->close();if($existing&&($existing['status']==='FILED'||($existing['status']==='LOCKED'&&$status!=='FILED')))throw new DomainException('Locked or filed contribution periods are immutable');
    $allowed=[null=>['DRAFT'],'DRAFT'=>['DRAFT','REVIEWED'],'REVIEWED'=>['REVIEWED','LOCKED'],'LOCKED'=>['FILED'],'FILED'=>[]];if(!in_array($status,$allowed[$existing['status']??null]??[],true))throw new DomainException('Invalid contribution period status transition');$configId=(int)$config['id'];$basisKind=$config['basis_kind'];$rate=$config['rate'];
    if($existing){$id=(int)$existing['id'];$s=$conn->prepare("UPDATE erp_contribution_periods SET config_id=?,basis_kind=?,basis_amount=?,rate=?,calculated_amount=?,status=?,notes=?,reviewed_by=IF(?='REVIEWED',COALESCE(reviewed_by,?),reviewed_by),reviewed_at=IF(?='REVIEWED',COALESCE(reviewed_at,NOW()),reviewed_at),locked_by=IF(?='LOCKED',COALESCE(locked_by,?),locked_by),locked_at=IF(?='LOCKED',COALESCE(locked_at,NOW()),locked_at),filed_by=IF(?='FILED',COALESCE(filed_by,?),filed_by),filed_at=IF(?='FILED',COALESCE(filed_at,NOW()),filed_at) WHERE id=? AND user_id=?");$s->bind_param('isdddsssississisii',$configId,$basisKind,$basis,$rate,$amount,$status,$notes,$status,$actorId,$status,$status,$actorId,$status,$status,$actorId,$status,$id,$uid);
    }else{$s=$conn->prepare("INSERT INTO erp_contribution_periods(user_id,config_id,contribution,period_start,period_end,basis_kind,basis_amount,rate,calculated_amount,status,notes,reviewed_by,reviewed_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,IF(?='REVIEWED',NOW(),NULL),?)");$reviewed=$status==='REVIEWED'?$actorId:null;$s->bind_param('iissssdddssisi',$uid,$configId,$contribution,$start,$end,$basisKind,$basis,$rate,$amount,$status,$notes,$reviewed,$status,$actorId);}
    $s->execute();if(!$existing)$id=(int)$s->insert_id;$s->close();auditLog($conn,$uid,$actorId,'CONTRIBUTION_PERIOD.'.$status,'CONTRIBUTION_PERIOD',$id,$existing?:null,['contribution'=>$contribution,'period_start'=>$start,'period_end'=>$end,'basis_kind'=>$basisKind,'basis_amount'=>$basis,'rate'=>$rate,'calculated_amount'=>$amount,'status'=>$status]);$conn->commit();jsonResponse(['success'=>true,'id'=>$id,'contribution'=>$contribution,'basis_kind'=>$basisKind,'basis_amount'=>(float)$basis,'rate'=>(float)$rate,'calculated_amount'=>(float)$amount,'status'=>$status]);
}catch(Throwable $e){if(isset($conn))try{$conn->rollback();}catch(Throwable $ignored){}reportFailureResponse($e,'Could not save the contribution period.','CONTRIBUTION_PERIOD_SAVE_FAILED');}
